"use client";
import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { z } from "zod";
import { useRouter } from "next/navigation";
import { useOfficer } from "@/app/navigation";
import { canEditFinance } from "@/lib/capabilities";
import { getJson, type OcrResult, type ScheduleGroup, type ScheduleOption, type Transaction } from "@/lib/client-types";
import { allowedDocumentTypes, DRAFT_KEY, draftSchema } from "@/lib/ocr-draft";
type ReviewItem = { particular: string; quantity: string; unit_cost: string; amount: string; confidence: number; scheduleId: string };
type Review = { file: File; preview: string; scanId?: number; result?: OcrResult; fields: Record<string,string>; rows: ReviewItem[]; status: "ready" | "processing" | "processed" | "manual" | "failed"; error?: string; confirmed: boolean };
const BATCH_KEY = "finance-ocr-batch-review";
const savedBatch = z.object({ term: z.string(), schedule: z.string(), mode: z.string(), type: z.string(), pipeline: z.string(), parent: z.string().optional(), rows: z.array(z.object({ name: z.string(), scanId: z.number().int().positive(), fields: z.record(z.string(),z.string()), rows: z.array(z.object({ particular: z.string(), quantity: z.string(), unit_cost: z.string(), amount: z.string(), confidence: z.number(), scheduleId: z.string() })), status: z.enum(["processed","manual","failed"]), error: z.string().optional(), confirmed: z.boolean() })) });
export default function OcrWorkspace() {
  const officer = useOfficer(), router = useRouter(); const canEdit = canEditFinance(officer);
  const [sides,setSides] = useState<ScheduleOption[]>([]), [schedule,setSchedule] = useState(""), [mode,setMode] = useState("PRIMARY"), [type,setType] = useState("DV"), [pipeline,setPipeline] = useState("printed"), [reviews,setReviews] = useState<Review[]>([]), [selected,setSelected] = useState(0), [busy,setBusy] = useState(false), [message,setMessage] = useState("");
  const urls = useRef<string[]>([]);
  const [parents,setParents] = useState<Transaction[]>([]), [parent,setParent] = useState("");
  useEffect(() => { Promise.all([getJson<Transaction[]>("/api/transactions/vouchers"),getJson<Transaction[]>("/api/transactions/receipts")]).then(([dvs,ars]) => setParents([...dvs,...ars])).catch(error => setMessage(error.message)); }, []);
  useEffect(() => { getJson<ScheduleGroup[]>("/api/schedules").then(groups => setSides(groups.filter(group => !group.is_closed && group.academic_year === officer?.term).flatMap(group => group.schedules))).catch(error => setMessage(error.message)); return () => { urls.current.forEach(url => URL.revokeObjectURL(url)); }; }, [officer?.term]);
  useEffect(() => {
    Promise.resolve().then(() => {
      const raw = sessionStorage.getItem(BATCH_KEY); if (!raw) return;
      try { const saved = savedBatch.parse(JSON.parse(raw)); if (saved.term !== officer?.term) { sessionStorage.removeItem(BATCH_KEY); return; }
        setSchedule(saved.schedule); setMode(saved.mode); setType(saved.type); setPipeline(saved.pipeline); setParent(saved.parent || "");
        setReviews(saved.rows.map(row => ({ ...row, file: new File([],row.name), preview: "/api/storage?scanId=" + row.scanId })));
        setMessage("Your remaining saved batch reviews have been restored. Unsaved files must be chosen again."); sessionStorage.removeItem(BATCH_KEY);
      } catch { sessionStorage.removeItem(BATCH_KEY); }
    });
  }, [officer?.term]);
  const direction = sides.find(side => String(side.id) === schedule)?.type || "OUTFLOW";
  const types = allowedDocumentTypes(direction, mode), sheet = type === "COLLECTION_SHEET" || type === "SALES_SHEET";
  const current = reviews[selected];
  function context(nextSchedule: string, nextMode: string) { const nextDirection = sides.find(side => String(side.id) === nextSchedule)?.type || "OUTFLOW"; setSchedule(nextSchedule); setMode(nextMode); setParent(""); setType(allowedDocumentTypes(nextDirection,nextMode)[0]); }
  function choose(files: FileList | null) {
    if (!files) return; const list = Array.from(files); if (list.length > (mode === "PRIMARY" ? 1 : 10)) { setMessage("Choose one primary document or up to ten supporting files."); return; }
    if (list.some(file => !["image/png","image/jpeg","image/webp"].includes(file.type) || !file.size || file.size > 10 * 1024 * 1024)) { setMessage("Every file must be a nonempty PNG/JPEG/WebP image no larger than 10 MB."); return; }
    urls.current.forEach(url => URL.revokeObjectURL(url)); urls.current = list.map(file => URL.createObjectURL(file)); setReviews(list.map((file,index) => ({ file, preview: urls.current[index], fields: {}, rows: [], status: "ready", confirmed: false }))); setSelected(0); setMessage("");
  }
  function update(index: number, patch: Partial<Review>) { setReviews(previous => previous.map((row,i) => i === index ? { ...row, ...patch } : row)); }
  async function process(index: number, manual = false) {
    const row = reviews[index]; if (!row) return; update(index, { status: "processing", error: undefined, confirmed: false });
    try {
      const form = new FormData(); if (row.scanId) form.append("scan_id", String(row.scanId)); else form.append("file",row.file);
      form.append("pipeline", manual || sheet ? "manual" : pipeline); form.append("schedule_id",schedule); form.append("mode",mode); form.append("document_type",type);
      const response = await fetch("/api/ocr/process", { method: "POST", body: form }); const data = await response.json();
      if (!response.ok) { update(index, { scanId: data.scanId || row.scanId, status: "failed", error: data.error || "Extraction failed." }); return; }
      const result = data.extractedData as OcrResult | null;
      update(index, { scanId: data.scanId, result: result || undefined, fields: result ? Object.fromEntries(result.fields.map(field => [field.field_name,field.value])) : row.fields, rows: result ? result.line_items.map(item => ({ particular: item.particular, quantity: item.quantity == null ? "" : String(item.quantity), unit_cost: item.unit_cost == null ? "" : String(item.unit_cost), amount: String(item.amount), confidence: item.confidence, scheduleId: schedule })) : row.rows, status: result ? "processed" : "manual" });
    } catch (error) { update(index, { status: "failed", error: error instanceof Error ? error.message : "Request failed." }); }
  }
  async function run(manual = false, retryOnly = false) {
    if (!canEdit || !schedule || busy) return; setBusy(true); setMessage("");
    const queue = reviews.map((row,index) => ({ row,index })).filter(({row}) => retryOnly ? row.status === "failed" : row.status === "ready").map(({index}) => index);
    if (mode === "PRIMARY" && reviews.length !== 1) { setMessage("Primary transactions use one document at a time."); setBusy(false); return; }
    let position = 0; await Promise.all([0,1].map(async () => { while (position < queue.length) { const index = queue[position++]; await process(index, manual); } })); setBusy(false);
  }
  function continueDraft() {
    if (!current?.scanId || !current.confirmed) return;
    try { const kind = mode === "PRIMARY" ? type : sheet ? "SHEET" : "RECEIPT"; const draft = draftSchema.parse({ kind, scanId: current.scanId, scheduleId: Number(schedule), documentType: type, parentId: parent ? Number(parent) : undefined, parentVersion: parent ? parents.find(row => row.id === Number(parent) && String(row.schedule.id) === schedule)?.version : undefined, fields: current.fields, items: current.rows.map(row => ({ particular: row.particular, quantity: row.quantity === "" ? null : Number(row.quantity), unit_cost: row.unit_cost === "" ? null : Number(row.unit_cost), amount: Number(row.amount), confidence: row.confidence, scheduleId: Number(row.scheduleId) })) }); sessionStorage.setItem(DRAFT_KEY, JSON.stringify(draft));
      const remaining = reviews.filter((row,index) => index !== selected && row.scanId && row.status !== "processing").map(row => ({ name: row.file.name, scanId: row.scanId, fields: row.fields, rows: row.rows, status: row.status, error: row.error, confirmed: row.confirmed }));
      sessionStorage.setItem(BATCH_KEY, JSON.stringify({ term: officer?.term, schedule, mode, type, pipeline, parent, rows: remaining })); router.push(mode === "PRIMARY" ? type === "DV" ? "/transactions/vouchers" : "/transactions/receipts" : "/supporting"); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not prepare draft."); }
  }
  return <main className="mx-auto max-w-7xl space-y-5 p-5 sm:p-8"><h1 className="text-3xl font-semibold">Record document & OCR review</h1><p className="text-sm text-gray-500">Choose a schedule first. Extraction produces drafts; only a confirmed finance form records money. Supporting evidence never adds a second inflow or expense.</p>{message && <p role="alert" className="border p-3 text-red-700">{message}</p>}
    <fieldset disabled={busy} className="finance-card grid gap-4 p-4 sm:grid-cols-3"><label>Schedule<select disabled={reviews.length > 0} className="finance-input mt-1" value={schedule} onChange={event => context(event.target.value,mode)}><option value="">Choose schedule…</option>{sides.map(side => <option value={side.id} key={side.id}>{side.type} · {side.label}</option>)}</select></label><label>Document mode<select disabled={reviews.length > 0} className="finance-input mt-1" value={mode} onChange={event => context(schedule,event.target.value)}><option value="PRIMARY">Primary AR / DV</option><option value="SUPPORTING">Supporting evidence / batch</option></select></label><label>Confirmed document type<select disabled={reviews.length > 0} className="finance-input mt-1" value={type} onChange={event => setType(event.target.value)}>{types.map(value => <option key={value}>{value}</option>)}</select></label><label className="sm:col-span-2">Files<input disabled={!schedule || !canEdit} type="file" multiple={mode === "SUPPORTING"} accept="image/png,image/jpeg,image/webp" className="block mt-2" onChange={event => choose(event.target.files)} /></label><label>Recognition<select disabled={sheet} className="finance-input mt-1" value={sheet ? "manual" : pipeline} onChange={event => setPipeline(event.target.value)}><option value="printed">Printed PaddleOCR</option><option value="handwritten">Handwriting baseline (manual review)</option><option value="manual">Manual entry</option></select></label></fieldset>
    {mode === "SUPPORTING" && <label className="block text-sm">Common parent for this batch (optional)<select disabled={busy || reviews.length > 0} value={parent} onChange={event => setParent(event.target.value)} className="finance-input mt-1"><option value="">Link each document later</option>{parents.filter(row => String(row.schedule.id) === schedule).map(row => <option key={row.id} value={row.id}>{row.control_number}</option>)}</select><span className="text-xs text-gray-500">Applied as a draft choice only. Sheet coverage still requires an explicit amount in the editor.</span></label>}
    <p className="text-xs text-gray-500">Collection/sales sheets always bypass OCR. Handwriting uses the same pretrained recognizer; accuracy on your handwriting has not been established. Batch processing uses at most two requests; failed files retain their scan IDs.</p>
    <div className="flex flex-wrap gap-3"><button type="button" className="finance-secondary" disabled={busy || !reviews.length} onClick={() => { setReviews([]); sessionStorage.removeItem(BATCH_KEY); setMessage("Saved scans remain available in the reconciliation queue."); }}>Start another batch</button><button className="finance-primary" disabled={!canEdit || !schedule || !reviews.length || busy} onClick={() => run(pipeline === "manual")}>{busy ? "Processing…" : "Process ready files"}</button><button className="finance-secondary" disabled={!canEdit || busy || !reviews.some(row => row.status === "failed")} onClick={() => run(false,true)}>Retry failed files only</button></div>
    {!!reviews.length && <div className="flex flex-wrap gap-2">{reviews.map((row,index) => <button key={index} className={selected === index ? "finance-primary" : "finance-secondary"} onClick={() => setSelected(index)}>{row.file.name} · {row.status}{row.scanId ? " · scan #" + row.scanId : ""}</button>)}</div>}
    {current && <div className="grid items-start gap-5 lg:grid-cols-2"><section className="finance-card p-4"><h2 className="mb-3 font-semibold">Original document</h2><Image unoptimized width={800} height={1100} src={current.preview} alt={current.file.name} className="h-auto w-full" />{current.scanId && <a className="underline text-blue-600" target="_blank" rel="noreferrer" href={"/api/storage?scanId=" + current.scanId}>Open saved original</a>}</section><section className="finance-card space-y-4 p-5"><h2 className="font-semibold">Editable review</h2>{current.error && <p role="alert" className="text-red-700">{current.error}</p>}{current.result && <p className="text-sm">Recognition confidence {Math.round(current.result.overall_confidence * 100)}%. This is not accounting accuracy.</p>}
      <fieldset disabled={busy || !canEdit || !current.scanId} className="space-y-4">{(sheet ? ["purpose","amount"] : ["control_number","date","purpose","amount"]).map(field => <label className="block text-sm" key={field}>{sheet && field === "purpose" ? "Sheet context / label" : field.replaceAll("_"," ")}<input className="finance-input mt-1" type={field === "date" ? "date" : "text"} value={current.fields[field] || ""} onChange={event => update(selected, { fields: { ...current.fields, [field]: event.target.value }, confirmed: false })} /></label>)}
      {mode === "SUPPORTING" && !sheet && <><h3 className="font-semibold">Receipt items</h3>{current.rows.map((row,index) => <div className="grid gap-2 rounded border p-3 sm:grid-cols-2" key={index}>{(["particular","quantity","unit_cost","amount"] as const).map(field => <label className="text-sm" key={field}>{field === "amount" ? "Recognized line total" : field.replaceAll("_"," ")}<input className="finance-input" type={field === "particular" ? "text" : "number"} step="0.01" min="0" value={row[field]} onChange={event => update(selected, { rows: current.rows.map((item,i) => i === index ? { ...item,[field]: event.target.value } : item), confirmed: false })} /></label>)}<label className="text-sm">Item schedule<select className="finance-input" value={row.scheduleId} onChange={event => update(selected, { rows: current.rows.map((item,i) => i === index ? { ...item,scheduleId: event.target.value } : item), confirmed: false })}>{sides.filter(side => side.type === "OUTFLOW").map(side => <option key={side.id} value={side.id}>{side.label}</option>)}</select></label><button type="button" className="underline text-red-700" onClick={() => update(selected,{ rows: current.rows.filter((_,i) => i !== index), confirmed: false })}>Remove row</button>{(!row.quantity || !row.unit_cost || row.confidence < .8) && <p className="text-xs text-amber-700">Check original; missing quantities/unit costs stay blank.</p>}</div>)}<button type="button" className="finance-secondary" onClick={() => update(selected,{ rows: [...current.rows,{ particular: "",quantity: "",unit_cost: "",amount: "",confidence: 0,scheduleId: schedule }],confirmed: false })}>Add item</button></>}
      <div className="flex flex-wrap gap-2"><button type="button" className="finance-secondary" onClick={() => update(selected,{ fields: {},rows: [],result: undefined,confirmed: false })}>Discard predictions, keep scan</button>{current.status === "failed" && <button type="button" className="finance-secondary" onClick={async () => { setBusy(true); await process(selected,true); setBusy(false); }}>Use saved scan manually</button>}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={current.confirmed} onChange={event => update(selected,{ confirmed: event.target.checked })} />I reviewed this document and will confirm its values in the editor.</label><button disabled={!current.confirmed} className="finance-primary" onClick={continueDraft}>Continue to {mode === "PRIMARY" ? type + " form" : "support editor"}</button></fieldset>
      {current.result && <details><summary className="cursor-pointer">Machine text</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{current.result.raw_text}</pre></details>}
    </section></div>}
  </main>;
}
