"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useOfficer } from "./navigation";
import { getJson, type Transaction, type ScheduleGroup } from "@/lib/client-types";
type Row = Transaction & { type: "DV" | "AR"; support_total: string; difference: string; incomplete: boolean; mismatch: boolean };
type Data = { records: Row[]; count: number; pages: number; totals: Record<string, string | number>; supporting: { id: number; internal_receipt_number: string; reference_number: string; scan_file_id: number }[]; outstanding_sheets: { id: number; context_label: string; remaining: string }[] };
export default function FinanceBrowser({ title = "Financial records", initial = {} }: { title?: string; initial?: Record<string,string> }) {
  const officer = useOfficer();
  const [filters, setFilters] = useState({ term: officer?.term || "all", q: "", from: "", to: "", activity: "", semester: "", schedule_id: "", group_id: "", status: "all", kind: "all", ...initial });
  const [active, setActive] = useState(filters), [page, setPage] = useState(1), [loaded, setLoaded] = useState<{ query: string; data: Data } | null>(null), [refresh, setRefresh] = useState(0), [error, setError] = useState("");
  const [groups, setGroups] = useState<ScheduleGroup[]>([]);
  const params = useCallback(() => new URLSearchParams({ ...active, page: String(page), page_size: "25" }).toString(), [active,page]);
  useEffect(() => { let cancelled = false; const query = params(); getJson<Data>("/api/finance?" + query).then(data => { if (!cancelled) { setError(""); setLoaded({ query, data }); } }).catch(error => { if (!cancelled) setError(error.message); }); return () => { cancelled = true; }; }, [params,refresh]);
  const data = loaded?.query === params() ? loaded.data : null;
  useEffect(() => { getJson<ScheduleGroup[]>("/api/schedules").then(setGroups).catch(error => setError(error.message)); }, []);
  const terms = [...new Set([officer?.term || "", ...groups.map(group => group.academic_year)])].filter(Boolean);
  return <main className="mx-auto max-w-7xl space-y-6 p-5 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-gray-500">Recorded net movement is inflow minus outflow, not certified cash on hand. Totals use the same filters as the records.</p></div><Link href="/ocr" className="finance-secondary">Record document</Link></div>
    <form className="finance-card grid gap-3 p-4 sm:grid-cols-3 lg:grid-cols-4" onSubmit={event => { event.preventDefault(); setPage(1); setActive(filters); }}>
      <label className="text-sm">Term<select className="finance-input mt-1" value={filters.term} onChange={event => setFilters({ ...filters, term: event.target.value, schedule_id: "", group_id: "" })}><option value="all">All periods</option>{terms.map(term => <option key={term}>{term}</option>)}</select></label>
      <label className="text-sm">Control / reference / purpose<input className="finance-input mt-1" value={filters.q} maxLength={100} onChange={event => setFilters({ ...filters, q: event.target.value })} /></label>
      {(["from", "to"] as const).map(field => <label key={field} className="text-sm">{field === "from" ? "Start date" : "End date"}<input type="date" className="finance-input mt-1" value={filters[field]} onChange={event => setFilters({ ...filters, [field]: event.target.value })} /></label>)}
      <label className="text-sm">Schedule<select className="finance-input mt-1" value={filters.schedule_id} onChange={event => setFilters({ ...filters, schedule_id: event.target.value })}><option value="">All schedules</option>{groups.filter(group => filters.term === "all" || group.academic_year === filters.term).flatMap(group => group.schedules.map(side => <option key={side.id} value={side.id}>{group.schedule_number} · {side.label}</option>))}</select></label>
      {(["activity", "semester", "status", "kind"] as const).map(field => <label className="text-sm capitalize" key={field}>{field}<select className="finance-input mt-1" value={filters[field]} onChange={event => setFilters({ ...filters, [field]: event.target.value })}>{(field === "activity" ? ["", "IGP", "MEMBERSHIP", "FINES", "EVENTS"] : field === "semester" ? ["", "FIRST", "SECOND", "SUMMER"] : field === "status" ? ["all", "verified", "unverified", "incomplete", "mismatch"] : ["all", "DV", "AR"]).map(value => <option key={value} value={value}>{value || "All"}</option>)}</select></label>)}
      <button className="finance-primary">Apply filters</button><button type="button" className="finance-secondary" onClick={() => setRefresh(value => value + 1)}>Refresh</button>
    </form>
    {error && <p role="alert" className="rounded border border-red-200 p-3 text-red-700">{error}</p>}
    {data && <><div className="grid gap-3 sm:grid-cols-3">{[["Recorded inflow",data.totals.inflow],["Recorded outflow",data.totals.outflow],["Recorded net movement",data.totals.net_movement],["Verified inflow",data.totals.verified_inflow],["Verified outflow",data.totals.verified_outflow],["Awaiting verification",data.totals.unverified]].map(([label,value]) => <section key={label} className="finance-card p-4"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums">{label === "Awaiting verification" ? value : "PHP " + value}</p></section>)}</div>
    <p className="text-sm">{data.totals.incomplete} missing support · {data.totals.mismatched} amount mismatches · {data.outstanding_sheets.length} sheets with outstanding coverage. Flags do not prevent valid saves or Auditor decisions.</p>
    <div className="flex flex-wrap gap-3"><a href={"/api/finance/export?" + params()} className="finance-secondary">Download supplementary totals</a><a href={"/api/finance/export?attention=1&" + params()} className="finance-secondary">Download attention report</a></div>
    <div className="finance-card overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr>{["Record","Date","Schedule","Amount","Support","Difference","Flags"].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{data.records.map(row => <tr key={row.type + row.id} className="border-t"><td className="p-3"><Link className="text-blue-600 underline" href={"/transactions/" + row.type + "/" + row.id}>{row.type} {row.control_number}</Link></td><td className="p-3">{row.date.slice(0,10)}</td><td className="p-3">{row.schedule.label}</td><td className="p-3">{row.amount}</td><td className="p-3">{row.support_total}</td><td className="p-3">{row.difference}</td><td className="p-3">{row.incomplete ? "Missing evidence · " : ""}{row.mismatch ? "Mismatch · " : ""}{row.is_verified ? "Verified" : "Unverified"}</td></tr>)}</tbody></table>{!data.records.length && <p className="p-5 text-gray-500">No transactions match these filters.</p>}</div>
    <div className="flex items-center gap-3"><button className="finance-secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {data.pages} · {data.count} records</span><button className="finance-secondary" disabled={page >= data.pages} onClick={() => setPage(page + 1)}>Next</button></div>
    {!!data.supporting.length && <section className="finance-card p-4"><h2 className="font-semibold">Supporting receipts in this scope</h2><p className="text-xs text-gray-500">Includes mixed and unlinked items. Evidence does not add to transaction totals. Showing up to 100 documents.</p>{data.supporting.map(doc => <p key={doc.id} className="mt-2"><Link href={"/supporting?kind=RECEIPT&id=" + doc.id} className="underline">{doc.internal_receipt_number} · {doc.reference_number}</Link> · <a className="text-blue-600 underline" target="_blank" rel="noreferrer" href={"/api/storage?scanId=" + doc.scan_file_id}>Original</a></p>)}</section>}
    {!!data.outstanding_sheets.length && <section className="finance-card p-4"><h2 className="font-semibold">Outstanding sheet coverage</h2><p className="text-xs text-gray-500">Term ownership and linked schedules determine sheet scope; date filters apply to dated records, not an undated sheet.</p>{data.outstanding_sheets.map(sheet => <p className="mt-2" key={sheet.id}><Link className="underline" href={"/supporting?kind=SHEET&id=" + sheet.id}>{sheet.context_label}</Link> · PHP {sheet.remaining} remaining</p>)}</section>}</>}
  </main>;
}
