ALTER TABLE `users`
  MODIFY `role_type` ENUM('ADMIN', 'OFFICER', 'STUDENT', 'ADVISER', 'EXTERNAL') NOT NULL,
  ADD COLUMN `is_active` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `deleted_at` DATETIME(3) NULL,
  ADD COLUMN `auth_version` INTEGER NOT NULL DEFAULT 0;
