"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { useOfficer } from "@/app/navigation";
import { canEditFinance, canVerifyFinance } from "@/lib/capabilities";
import { getJson, type Transaction, type OrphanDocument } from "@/lib/client-types";
type Detail = Transaction & { type: "DV" | "AR"; deleted_at: string | null; historical_evidence: { scan_id: number; document_id: number; kind: string; label: string }[]; evidence: { kind: string; document_id: number; scan_id: number; label: string; amount: string; total?: string; remaining?: string }[]; support_total: string; difference: string; incomplete: boolean; mismatch: boolean; verification_events: { id: number; event: string; reason: string | null; occurred_at: string; user: { name: string } }[]; mutation_history: { id: number; action: string; occurred_at: string; user_id: number; before: unknown; after: unknown }[] };
export default function TransactionDetail({ kind,id }: { kind: string; id: string }) {
  const officer = useOfficer(); const [data, setData] = useState<Detail | null>(null), [orphans,setOrphans] = useState<OrphanDocument[]>([]), [error,setError] = useState(""), [busy,setBusy] = useState(false), [scan,setScan] = useState<number | null>(null), [selected,setSelected] = useState(""), [allocation,setAllocation] = useState("");
  const load = useCallback(async () => { const row = await getJson<Detail>("/api/finance/transactions/" + kind + "/" + id); setData(row); setScan(row.scan_file?.id || row.evidence[0]?.scan_id || null); setOrphans(await getJson<OrphanDocument[]>("/api/documents/orphan?term=" + encodeURIComponent(row.schedule.group?.academic_year || "all") + "&schedule_id=" + row.schedule.id)); }, [kind,id]);
  useEffect(() => { Promise.resolve().then(load).catch(error => setError(error.message)); }, [load]);
  if (!data) return <main className="p-6">{error || "Loading transaction…"}</main>;
  const open = !data.deleted_at && !data.schedule.group?.is_closed && data.schedule.group?.academic_year === officer?.term;
  const edit = open && canEditFinance(officer), verify = open && canVerifyFinance(officer);
  async function action(url: string, body: unknown) { setBusy(true); setError(""); try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Action failed."); await load(); } catch (error) { setError(error instanceof Error ? error.message : "Action failed."); } finally { setBusy(false); } }
  async function link() { if (!data) return; const row = orphans.find(row => row.kind + ":" + row.id === selected); if (!row) return; await action(row.kind === "SCAN" ? "/api/documents/orphan/link" : "/api/documents/supporting/link", row.kind === "SCAN" ? { scan_id: row.scan_id, transaction_type: kind, transaction_id: data.id, version: data.version } : { kind: row.kind, document_id: row.id, document_version: row.document_version, transaction_id: data.id, version: data.version, amount_covered: allocation }); }
  return <main className="mx-auto max-w-7xl space-y-5 p-6"><Link href="/archive" className="underline">Back to records</Link><h1 className="text-3xl font-semibold">{data.type} {data.control_number}</h1>{error && <p role="alert" className="border p-3 text-red-700">{error} Your reviewed version was not overwritten. <button className="underline" onClick={() => load().catch(error => setError(error.message))}>Review latest record</button></p>}{data.deleted_at && <p className="bg-amber-50 p-3">Deleted from active totals. Evidence and audit history are retained.</p>}
    <div className="grid items-start gap-5 lg:grid-cols-2"><section className="finance-card space-y-3 p-4"><h2 className="font-semibold">Original evidence</h2>{!!data.historical_evidence.length && <p className="text-xs text-gray-500">Previous support scans are retained in this viewer and correction history. Only current links count toward support totals.</p>}<div className="flex flex-wrap gap-2">{data.scan_file && <button className="finance-secondary" onClick={() => setScan(data.scan_file!.id)}>Primary scan</button>}{[...new Set([...data.evidence,...data.historical_evidence].map(item => item.scan_id))].map(scanId => <button key={scanId} className="finance-secondary" onClick={() => setScan(scanId)}>Support #{scanId}</button>)}</div>{scan ? <><a className="text-blue-600 underline" href={"/api/storage?scanId=" + scan} target="_blank" rel="noreferrer">Open original image</a><Image unoptimized width={800} height={1100} className="h-auto w-full" src={"/api/storage?scanId=" + scan} alt="Original financial evidence" /></> : <p>No scan is attached.</p>}</section>
    <section className="finance-card space-y-4 p-5"><h2 className="font-semibold">Recorded values · version {data.version}</h2><p>{data.date.slice(0,10)} · {data.schedule.label}</p><p>{data.purpose}</p><dl className="grid grid-cols-2 gap-3"><dt>Recorded amount</dt><dd>PHP {data.amount}</dd><dt>Linked support</dt><dd>PHP {data.support_total}</dd><dt>Difference (record minus support)</dt><dd>PHP {data.difference}</dd><dt>Verification</dt><dd>{data.is_verified ? "Verified" : "Unverified"}</dd></dl><p className="rounded bg-amber-50 p-3 text-sm">{data.incomplete ? "Missing supporting evidence. " : ""}{data.mismatch ? "Supporting amount differs. " : ""}Flags inform review and do not block Auditor decisions.</p>{data.evidence.map((item,index) => <div className="border-t pt-2" key={index}><p>{item.label} · PHP {item.amount}</p>{item.remaining && <p className="text-xs">Sheet total {item.total}; remaining across all ARs {item.remaining}</p>}<Link className="text-sm underline" href={"/supporting?kind=" + item.kind + "&id=" + item.document_id}>Open support / edit / unlink</Link></div>)}
      <button disabled={!verify || busy} className="finance-primary" onClick={() => action("/api/verification/toggle", { transaction_id: data.id, type: data.type, version: data.version, status: !data.is_verified })}>{data.is_verified ? "Unverify" : "Verify"} this reviewed version</button>
      {edit && <fieldset disabled={busy} className="space-y-2 border-t pt-4"><legend className="font-semibold">Attach available evidence</legend><select className="finance-input" value={selected} onChange={event => setSelected(event.target.value)}><option value="">Choose evidence…</option>{orphans.filter(row => row.kind === "SCAN" ? !data.scan_file : kind === "DV" ? row.kind === "PARTICULAR" : row.kind === "SHEET").map(row => <option key={row.kind + row.id} value={row.kind + ":" + row.id}>{row.kind} · {row.file_path}{row.remaining ? " · remaining PHP " + row.remaining : ""}</option>)}</select>{selected.startsWith("SHEET:") && <label className="block">Coverage amount<input className="finance-input" value={allocation} onChange={event => setAllocation(event.target.value)} type="number" min="0.01" step="0.01" /></label>}<button className="finance-secondary" disabled={!selected} onClick={link}>Attach to this transaction</button></fieldset>}
    </section></div>
    <section className="finance-card p-5"><h2 className="font-semibold">Append-only verification history</h2>{data.verification_events.map(event => <p key={event.id} className="mt-2 text-sm">{event.occurred_at} · {event.user.name} · {event.event}{event.reason ? " · " + event.reason : ""}</p>)}{!data.verification_events.length && <p className="mt-2 text-sm">No verification actions recorded.</p>}</section>
    <section className="finance-card p-5"><h2 className="font-semibold">Correction and evidence history</h2>{data.mutation_history.map(event => <details key={event.id} className="mt-3 border-t pt-2"><summary className="cursor-pointer text-sm">{event.occurred_at} · actor #{event.user_id} · {event.action}</summary><pre className="max-h-72 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify({ before: event.before, after: event.after }, null, 2)}</pre></details>)}</section>
  </main>;
}
